services:
  redis-stack:
    image: redis/redis-stack:7.2.0-v8
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    deploy:
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 128mb
    volumes:
      - "depot-data:/data"
volumes:
  depot-data:
    driver: local
